// app/projects/page.tsx
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import * as motion from "motion/react-client";
import { Badge } from "@/components/ui";
import { ProjectsList } from "@/data/projects-list";
import React from "react";

export const metadata: Metadata = {
    title: process.env.PAGE_TITLE ? process.env.PAGE_TITLE + " | Projects" : "Froilan | Software Engineer | Projects",
    description: "A showcase of Froilan's projects and contributions.",
    keywords: ["Froilan's Projects", "Froilan's Showcase", "Froilan's Contributions"],
};

function Projects() {
    return (
        <main className="py-10 w-11/12 max-w-7xl gap-2 flex flex-col md:grid md:grid-cols-2">
            <Link
                href={"/"}
                className="flex items-center gap-2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200"
            >
                <ArrowLeft size={15} />
                <h1 className="text-sm">Back</h1>
            </Link>
            <div className="col-span-2 w-full flex flex-col gap-5">
                <h1 className="text-2xl text-center font-bold">Projects</h1>
                <div className="col-span-2 grid grid-cols-1 lg:grid-cols-2 gap-2">
                    {ProjectsList.map((project, index) => {
                        return (
                            <motion.div
                                key={project.link}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -20 }}
                                transition={{
                                    duration: 0.3,
                                    ease: "easeOut",
                                    delay: index * 0.1,
                                }}
                                className="w-full h-full"
                            >
                                <Link
                                    href={project.link}
                                    key={project.projectLink}
                                    rel="noreferrer"
                                    className="flex gap-2 items-center p-5 rounded-md border transition duration-200"
                                >
                                    <div className="flex flex-col gap-1">
                                        <section>
                                            <Link
                                                href={project.projectLink}
                                                target="_blank"
                                                rel="noreferrer"
                                                className="text-base font-semibold hover:underline underline-offset-2"
                                            >
                                                {project.title}
                                            </Link>
                                        </section>
                                        <p className="text-sm">{project.description}</p>
                                        <div className="flex flex-wrap gap-2">
                                            {project.footerContent.map((footer) => (
                                                <Badge
                                                    key={footer.text}
                                                    variant="outline"
                                                    className="w-fit font-semibold text-xs flex flex-row gap-1 items-center"
                                                >
                                                    {footer.icon}
                                                    {footer.text}
                                                </Badge>
                                            ))}
                                        </div>
                                    </div>
                                </Link>
                            </motion.div>
                        );
                    })}
                </div>
            </div>
        </main>
    );
}

export default Projects;

// src/routes/projects/+page.svelte
<script lang="ts">
    import { ArrowLeft } from "lucide-svelte";
    import { Badge } from "$lib/components/ui/badge";
    import { ProjectsList } from "$lib/data/projects-list";
    import { fly, fade } from "svelte/transition";
</script>

<svelte:head>
    <title>Froilan | Projects</title>
</svelte:head>

<main class="py-10 w-11/12 max-w-7xl mx-auto gap-2 flex flex-col md:grid md:grid-cols-2">
    <a
        href="/"
        class="flex items-center gap-2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200 w-fit"
    >
        <ArrowLeft size={15} />
        <h1 class="text-sm">Back</h1>
    </a>
    <div class="col-span-2 w-full flex flex-col gap-5">
        <h1 class="text-2xl text-center font-bold">Projects</h1>
        <div class="col-span-2 grid grid-cols-1 lg:grid-cols-2 gap-2">
            {#each ProjectsList as project, index (project.pageLink)}
                <div
                    in:fly={{ y: 20, duration: 300, delay: index * 100 }}
                    out:fade={{ duration: 200 }}
                    class="w-full h-full"
                >
                    <div class="grid grid-cols-1 gap-2 items-center p-5 rounded-md border transition duration-200 w-full h-full">
                        <div class="flex flex-col gap-1 h-full justify-between">
                            <div class="flex flex-col gap-1">
                                <section class="flex justify-between w-full items-center">
                                    <p class="text-base font-semibold">{project.title}</p>
                                    <a
                                        class="text-base font-semibold hover:underline underline-offset-2"
                                        href={project.pageLink}
                                    >
                                        View
                                    </a>
                                </section>
                                <p class="text-sm">{project.description}</p>
                            </div>
                            <div class="flex flex-wrap gap-2 mt-auto pt-4">
                                {#each project.footerContent as footer}
                                    <Badge
                                        variant="outline"
                                        class="w-fit font-semibold text-xs flex flex-row gap-1 items-center"
                                    >
                                        {@const Icon = footer.icon}
                                        <Icon class="w-4 h-4" />
                                        {footer.text}
                                    </Badge>
                                {/each}
                            </div>
                        </div>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</main>
