// components/organisms/contact-me-card.tsx
import { Card, CardHeader, CardTitle, CardContent, Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui";
import { CredlyIcon, Github, HackerRank, Instagram, LeetCode, LinkedIn } from "@/components/atoms";
import { ArrowRight, Send } from "lucide-react";
import Link from "next/link";

export const ContactMe = ({ className }: { className?: string }) => {
    return (
        <div className={className}>
            <Card className="w-full h-full">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Send size={15} />
                        <span className="text-lg">Contact Me</span>
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="flex flex-col gap-5">
                        <div>
                            <h1>Email:</h1>
                            <div className="flex flex-col">
                                <Link
                                    className="underline underline-offset-1 font-bold"
                                    href="mailto:aquino.froilan.dev@outlook.com?subject=Contact%20from%20Website"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    aquino.froilan.dev@outlook.com
                                </Link>
                            </div>
                        </div>
                        <div>
                            <h1>Social Links:</h1>
                            <div className="grid grid-cols-3 gap-2">
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="Github link of the website owner"
                                            target="_blank"
                                            href="https://github.com/aquinofroilan"
                                        >
                                            <Github className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>GitHub</p>
                                    </TooltipContent>
                                </Tooltip>
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="Instagram Profile of the website owner"
                                            target="_blank"
                                            href="https://www.instagram.com/aquinofroilan_"
                                        >
                                            <Instagram className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Instagram</p>
                                    </TooltipContent>
                                </Tooltip>
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="LinkedIn link of the website owner"
                                            target="_blank"
                                            href="https://linkedin.com/in/aquinofroilan"
                                        >
                                            <LinkedIn className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>LinkedIn</p>
                                    </TooltipContent>
                                </Tooltip>
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="Credly link of the website owner"
                                            target="_blank"
                                            href="https://www.credly.com/users/froilan"
                                        >
                                            <CredlyIcon className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>Credly</p>
                                    </TooltipContent>
                                </Tooltip>
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="HackerRank link of the website owner"
                                            target="_blank"
                                            href="https://www.hackerrank.com/profile/froilanaquino"
                                        >
                                            <HackerRank className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>HackerRank</p>
                                    </TooltipContent>
                                </Tooltip>
                                <Tooltip>
                                    <TooltipTrigger>
                                        <Link
                                            className="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors"
                                            aria-label="LeetCode link of the website owner"
                                            target="_blank"
                                            href="https://leetcode.com/u/froilan_/"
                                        >
                                            <LeetCode className="w-5 h-5" />
                                        </Link>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>LeetCode</p>
                                    </TooltipContent>
                                </Tooltip>
                            </div>
                        </div>
                        <div>
                            <h1>Let&apos;s talk:</h1>
                            <Link
                                href="https://calendly.com/froilan/consultation"
                                className="group w-full justify-between flex items-center py-2 px-2 rounded-md mt-2 hover:bg-muted transition-colors"
                                aria-label="Schedule a consultation call via Calendly"
                            >
                                Schedule a call
                                <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" />
                            </Link>
                        </div>
                        {process.env.RESUME_CV_LINK && (
                            <div>
                                <h1>My Resume/CV:</h1>
                                <Link
                                    href={process.env.RESUME_CV_LINK}
                                    className="group w-full justify-between flex items-center py-2 px-2 rounded-md mt-2 hover:bg-muted transition-colors"
                                    aria-label="View resume or CV document"
                                >
                                    View my CV
                                    <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" />
                                </Link>
                            </div>
                        )}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
};

// src/lib/components/organisms/contact-me-card.svelte
<script lang="ts">
    import * as Card from '$lib/components/ui/card';
    import * as Tooltip from '$lib/components/ui/tooltip';
    import { ArrowRight, Send } from 'lucide-svelte';
    import { CredlyIcon, HackerRank, LeetCode, Github, Instagram, LinkedIn } from '$lib/components/atoms';
    
    let { class: className = '', RESUME_CV_LINK = '' } = $props<{ 
        class?: string;
        RESUME_CV_LINK?: string;
    }>();
</script>

<div class={className}>
    <Card.Root class="flex flex-col gap-3 h-full w-full">
        <Card.Header>
            <Card.Title class="flex justify-between items-center w-full">
                <Send size={15} />
                <span class="text-lg">Contact Me</span>
            </Card.Title>
        </Card.Header>
        <Card.Content>
            <div class="flex flex-col gap-5">
                <div>
                    <span class="text-xs">Email:</span>
                    <div class="flex flex-col">
                        <a
                            class="underline underline-offset-1"
                            href="mailto:aquino.froilan.dev@outlook.com?subject=Contact%20from%20Website"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <span class="text-xs">aquino.froilan.dev@outlook.com</span>
                        </a>
                    </div>
                </div>
                <div>
                    <span class="text-xs">Social Links:</span>
                    <div class="grid grid-cols-3 gap-2">
                        <Tooltip.Provider>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="Github link" target="_blank" href="https://github.com/aquinofroilan" class="w-full h-full flex justify-center items-center">
                                        <Github class="w-5 h-5" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">GitHub</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="Instagram link" target="_blank" href="https://www.instagram.com/aquinofroilan_" class="w-full h-full flex justify-center items-center">
                                        <Instagram class="w-5 h-5" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">Instagram</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="LinkedIn link" target="_blank" href="https://linkedin.com/in/aquinofroilan" class="w-full h-full flex justify-center items-center">
                                        <LinkedIn class="w-6 h-6 hover:scale-105 transition duration-200" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">LinkedIn</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="Credly link" target="_blank" href="https://www.credly.com/users/froilan" class="w-full h-full flex justify-center items-center">
                                        <CredlyIcon class="w-5 h-5" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">Credly</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="HackerRank link" target="_blank" href="https://www.hackerrank.com/profile/froilanaquino" class="w-full h-full flex justify-center items-center">
                                        <HackerRank class="w-5 h-5" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">HackerRank</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                            <Tooltip.Root>
                                <Tooltip.Trigger class="w-full justify-center flex items-center py-2 px-2 rounded-md hover:bg-muted transition-colors">
                                    <a aria-label="LeetCode link" target="_blank" href="https://leetcode.com/u/froilan_/" class="w-full h-full flex justify-center items-center">
                                        <LeetCode class="w-5 h-5" />
                                    </a>
                                </Tooltip.Trigger>
                                <Tooltip.Content>
                                    <span class="text-xs">LeetCode</span>
                                </Tooltip.Content>
                            </Tooltip.Root>
                        </Tooltip.Provider>
                    </div>
                </div>
                <div>
                    <span class="text-xs">Let's talk:</span>
                    <a
                        href="https://calendly.com/froilan/consultation"
                        class="group w-full justify-between flex items-center py-2 px-2 rounded-md mt-2 hover:bg-muted transition-colors"
                        aria-label="Schedule a consultation call via Calendly"
                    >
                        <span class="text-xs">Schedule a call</span>
                        <ArrowRight size={15} class="transition-transform group-hover:translate-x-1" />
                    </a>
                </div>
                {#if RESUME_CV_LINK}
                    <div>
                        <span class="text-xs">My Resume/CV:</span>
                        <a
                            href={RESUME_CV_LINK}
                            class="group w-full justify-between flex items-center py-2 px-2 rounded-md mt-2 hover:bg-muted transition-colors"
                            aria-label="View resume or CV document"
                        >
                            <span class="text-xs">View my CV</span>
                            <ArrowRight size={15} class="transition-transform group-hover:translate-x-1" />
                        </a>
                    </div>
                {/if}
            </div>
        </Card.Content>
    </Card.Root>
</div>
