// src/lib/components/organisms/certification-card.svelte
<script lang="ts">
	import { BadgeCheck, ArrowRightCircle } from 'lucide-svelte';
	import * as Card from '$lib/components/ui/card';

	let { class: className = '', credlyCerts = [] } = $props<{
		class?: string;
		credlyCerts?: { title: string; issuer: string; link: string }[];
	}>();
</script>

<div class={className}>
	<Card.Root class="h-full w-full">
		<Card.Header>
			<Card.Title class="flex w-full items-center justify-between gap-2">
				<div class="flex items-center gap-2">
					<BadgeCheck size={15} />
					<span class="text-lg">Certifications</span>
				</div>
				<a
					href="/certifications"
					class="flex items-center gap-2 text-xs text-neutral-500 transition duration-200 hover:text-neutral-700 md:text-base dark:text-neutral-400 dark:hover:text-neutral-200"
				>
					View All
					<ArrowRightCircle size={15} />
				</a>
			</Card.Title>
		</Card.Header>
		<Card.Content>
			<div class="flex w-full flex-col gap-4">
				{#each credlyCerts.slice(0, 4) as cert}
					<a
						href={cert.link}
						target="_blank"
						rel="noreferrer"
						class="group flex flex-col gap-1"
					>
						<h1 class="text-sm font-medium underline-offset-2 group-hover:underline">
							{cert.title}
						</h1>
						<p class="text-muted-foreground text-xs">{cert.issuer}</p>
					</a>
				{/each}
			</div>
		</Card.Content>
	</Card.Root>
</div>

// components/organisms/certification-card.tsx
import { BadgeCheckIcon, ArrowRightCircle } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui";
import Link from "next/link";
import { getCredlyCertifications } from "@/actions";

export const CertificationCard = async ({ className }: { className?: string }) => {
    const credlyCerts = await getCredlyCertifications();

    return (
        <div className={className}>
            <Card className="w-full h-full">
                <CardHeader>
                    <CardTitle className="flex gap-2 items-center justify-between w-full">
                        <div className="flex items-center gap-2">
                            <BadgeCheckIcon size={15} />
                            <span className="text-lg">Certifications</span>
                        </div>
                        <Link
                            href={"/certifications"}
                            className="text-xs md:text-base text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200 flex items-center gap-2"
                        >
                            View All
                            <ArrowRightCircle size={15} />
                        </Link>
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="w-full flex flex-col gap-4">
                        {credlyCerts.slice(0, 4).map((cert, i) => {
                            return (
                                <Link
                                    href={cert.link}
                                    target="_blank"
                                    rel="noreferrer"
                                    key={i}
                                    className="flex flex-col gap-1 group"
                                >
                                    <h1 className="text-sm font-medium group-hover:underline underline-offset-2">
                                        {cert.title}
                                    </h1>
                                    <p className="text-xs text-muted-foreground">{cert.issuer}</p>
                                </Link>
                            );
                        })}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
};
