// src/lib/components/organisms/projects-card.svelte
<script lang="ts">
    import { Badge } from '$lib/components/ui/badge';
    import * as Card from '$lib/components/ui/card';
    import { ArrowRightCircle, FolderCode } from 'lucide-svelte';
    import { ProjectsList } from '$lib/data/projects-list';

    let { class: className = '' } = $props<{ class?: string }>();
</script>

<div class={className}>
    <Card.Root class="flex flex-col gap-3 h-full w-full">
        <Card.Header>
            <Card.Title class="flex justify-between items-center w-full">
                <div class="flex items-center gap-2">
                    <FolderCode size={15} />
                    <span class="text-lg">Projects</span>
                </div>
                <a
                    href="/projects"
                    class="text-xs md:text-base text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200 flex items-center gap-2"
                >
                    View All
                    <ArrowRightCircle size={15} />
                </a>
            </Card.Title>
        </Card.Header>
        <Card.Content>
            <div class="flex flex-col gap-6">
                {#each ProjectsList.slice(0, 2) as project}
                    <div class="flex flex-col gap-2">
                        <section class="flex justify-between w-full items-center">
                            <p>{project.title}</p>
                            <a
                                href={project.pageLink}
                                rel="noreferrer"
                                class="text-xs text-muted-foreground hover:text-foreground transition-colors"
                            >
                                Details
                            </a>
                        </section>
                        <p class="text-xs text-muted-foreground line-clamp-2">{project.description}</p>
                        <div class="flex flex-wrap gap-2">
                            {#each project.footerContent as footer}
                                <Badge
                                    variant="secondary"
                                    class="w-fit text-[10px] px-2 py-0 h-5 flex flex-row gap-1 items-center font-normal"
                                >
                                    {@const Icon = footer.icon}
                                    <Icon class="w-5 h-5" />
                                    {footer.text}
                                </Badge>
                            {/each}
                        </div>
                    </div>
                {/each}
            </div>
        </Card.Content>
    </Card.Root>
</div>

// components/organisms/projects-card.tsx
import { Badge, Card, CardHeader, CardTitle, CardContent } from "@/components/ui";
import Link from "next/link";
import { ArrowRightCircle, FolderCode } from "lucide-react";
import { ProjectsList } from "@/data/projects-list";

/**
 * Render a motion-enabled "Projects" card that displays a header with a "View All" link and up to two project entries.
 *
 * Each project entry shows a title (opens in a new tab), a "Details" link, a short description, and a row of footer badges.
 *
 * @param className - Optional CSS classes applied to the root motion container
 * @returns A React element representing the Projects card with animated entrance/exit, header controls, and project entries
 */
function ProjectsCard({ className }: { className?: string }) {
    return (
        <div className={className}>
            <Card className="flex flex-col gap-3 h-full w-full">
                <CardHeader>
                    <CardTitle className="flex justify-between items-center w-full">
                        <div className="flex items-center gap-2">
                            <FolderCode size={15} />
                            <span className="text-lg">Projects</span>
                        </div>
                        <Link
                            href={"/projects"}
                            className="text-xs md:text-base text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200 flex items-center gap-2"
                        >
                            View All
                            <ArrowRightCircle size={15} />
                        </Link>
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="flex flex-col gap-6">
                        {ProjectsList.slice(0, 2).map((project) => (
                            <div className="flex flex-col gap-2" key={project.pageLink}>
                                <section className="flex justify-between w-full items-center">
                                    <Link
                                        href={project.projectLink}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="text-sm font-medium hover:underline underline-offset-2"
                                    >
                                        {project.title}
                                    </Link>
                                    <Link
                                        href={project.pageLink}
                                        rel="noreferrer"
                                        className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                                    >
                                        Details
                                    </Link>
                                </section>
                                <p className="text-xs text-muted-foreground line-clamp-2">{project.description}</p>
                                <div className="flex flex-wrap gap-2">
                                    {project.footerContent.map((footer) => (
                                        <Badge
                                            key={footer.text}
                                            variant="secondary"
                                            className="w-fit text-[10px] px-2 py-0 h-5 flex flex-row gap-1 items-center font-normal"
                                        >
                                            {footer.icon}
                                            {footer.text}
                                        </Badge>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}

export default ProjectsCard;
