// src/routes/techstack/+page.svelte
<script lang="ts">
    import { FRONTEND, BACKEND, DEVELOPER_TOOLS, DEVOPS } from "$lib/data/techstack-list";
    import * as Card from "$lib/components/ui/card";
    import { Badge } from "$lib/components/ui/badge";
    import { ArrowLeft } from "lucide-svelte";
    import { fly, fade } from "svelte/transition";
</script>

<svelte:head>
    <title>Froilan | TechStack</title>
</svelte:head>

<main class="py-10 w-11/12 max-w-7xl gap-2 flex flex-col mx-auto">
    <a
        href="/"
        class="flex items-center gap-2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200 w-fit"
    >
        <ArrowLeft size={15} />
        <h1 class="text-sm">Back</h1>
    </a>
    <div class="flex flex-col gap-5">
        <h1 class="text-2xl text-center font-bold">TechStack</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
            {#each [
                { title: 'Frontend', items: FRONTEND },
                { title: 'Backend', items: BACKEND },
                { title: 'DevOps & Cloud', items: DEVOPS },
                { title: 'Developer Tools', items: DEVELOPER_TOOLS }
            ] as section, index}
                <div
                    in:fly={{ y: 20, duration: 300, delay: (index + 1) * 100 }}
                    out:fade={{ duration: 200 }}
                    class="w-full h-full"
                >
                    <Card.Root class="h-full">
                        <Card.Header>
                            <Card.Title class="text-lg">{section.title}</Card.Title>
                        </Card.Header>
                        <Card.Content>
                            <div class="flex flex-wrap gap-2">
                                {#each section.items as item}
                                    <Badge variant="outline">{item}</Badge>
                                {/each}
                            </div>
                        </Card.Content>
                    </Card.Root>
                </div>
            {/each}
        </div>
    </div>
</main>

// app/techstack/page.tsx
import { FRONTEND, BACKEND, DEVELOPER_TOOLS, DEVOPS } from "@/data/techstack-array";
import { BentoGridItem, Badge } from "@/components/ui";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
function TechStack() {
    return (
        <main className="py-10 w-11/12 max-w-5xl gap-2 flex flex-col">
            <Link
                href={"/"}
                className="flex items-center gap-2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition duration-200"
            >
                <ArrowLeft size={15} />
                <h1 className="text-sm">Back</h1>
            </Link>
            <div className="col-Badge-2 flex flex-col gap-5">
                <h1 className="text-2xl text-center font-bold">TechStack</h1>
                <div className="col-Badge-2 grid grid-cols-1 md:grid-cols-2 gap-2">
                    <BentoGridItem
                        title={<h1 className="text-lg">Frontend</h1>}
                        description={
                            <div className="flex flex-wrap gap-2">
                                {FRONTEND.map((item) => (
                                    <Badge key={item} variant={"outline"}>
                                        {item}
                                    </Badge>
                                ))}
                            </div>
                        }
                    />
                    <BentoGridItem
                        title={<h1 className="text-lg">Backend</h1>}
                        description={
                            <div className="flex flex-wrap gap-2">
                                {BACKEND.map((item) => (
                                    <Badge key={item} variant={"outline"}>
                                        {item}
                                    </Badge>
                                ))}
                            </div>
                        }
                    />
                    <BentoGridItem
                        title={<h1 className="text-lg">DevOps & Cloud</h1>}
                        description={
                            <div className="flex flex-wrap gap-2">
                                {DEVOPS.map((item) => (
                                    <Badge key={item} variant={"outline"}>
                                        {item}
                                    </Badge>
                                ))}
                            </div>
                        }
                    />
                    <BentoGridItem
                        title={<h1 className="text-lg">Developer Tools</h1>}
                        description={
                            <div className="flex flex-wrap gap-2">
                                {DEVELOPER_TOOLS.map((item) => (
                                    <Badge key={item} variant={"outline"}>
                                        {item}
                                    </Badge>
                                ))}
                            </div>
                        }
                    />
                </div>
            </div>
        </main>
    );
}

export default TechStack;
